### ISSUE TITLE
Figma / sketch components

### ISSUE THREAD

**Issue by iotekas** [tailwindui/issues#47] opened 2020-03-06 16:47 UTC
**Additional context**
I would love to import tailwind ui components directly into sketch, it would improve my workflow a lot.

**Comment by DanHarrin** [comment] 2020-03-06 17:22
Please add your ideas to #21 and close this so that we have all conversation in the same place. Thank you.

**Comment by adamwathan** [comment] 2020-03-06 20:09
Duplicate of #21

**Closed by adamwathan** 2020-03-06 20:09 UTC
Labels: improvement
