### ISSUE TITLE
focus:shadow-outline

### ISSUE THREAD

**Issue by 8brandon** [tailwindui/issues#59] opened 2020-03-07 19:57 UTC
**What component (if applicable)**
- URL for category: 
- Component name: focus:shadow-outline

**Describe the bug**
I've noticed that focus:shadow-outline...  only works with certain colors. 
If you try to put a custom color from your theme it won't work. Also even black won't work for example (not that it would look good)

**To Reproduce**
Add a custom color OR black to focus:shadow-outline

**Expected behavior**
Color does not apply and transition doesn't happen.

**Browser/Device (if applicable)**
MacOS
Chrom

**Comment by adamwathan** [comment] 2020-03-18 15:28
Can you show me an example in code of what you're trying to do? I think you're saying classes like `focus:shadow-outline-black` don't work?

If so that's correct, here are the extra shadows that are included with the @tailwindcss/ui plugin:

```js
const boxShadow = {
  ...defaultTheme.boxShadow,
  solid: '0 0 0 2px currentColor',
  outline: `0 0 0 3px ${rgba(colors.blue[400], 0.45)}`,
  'outline-gray': `0 0 0 3px ${rgba(colors.gray[400], 0.45)}`,
  'outline-blue': `0 0 0 3px ${rgba(colors.blue[300], 0.45)}`,
  'outline-teal': `0 0 0 3px ${rgba(colors.teal[300], 0.45)}`,
  'outline-green': `0 0 0 3px ${rgba(colors.green[300], 0.45)}`,
  'outline-yellow': `0 0 0 3px ${rgba(colors.yellow[300], 0.45)}`,
  'outline-orange': `0 0 0 3px ${rgba(colors.orange[300], 0.45)}`,
  'outline-red': `0 0 0 3px ${rgba(colors.red[300], 0.45)}`,
  'outline-pink': `0 0 0 3px ${rgba(colors.pink[300], 0.45)}`,
  'outline-purple': `0 0 0 3px ${rgba(colors.purple[300], 0.45)}`,
  'outline-indigo': `0 0 0 3px ${rgba(colors.indigo[300], 0.45)}`,
}
```

If you want to create a custom outline shadow using a custom color from your theme, you'll need to add that custom box shadow yourself following the instructions in the Tailwind docs:

https://tailwindcss.com/docs/theme/#extending-the-default-theme

Thanks!

**Comment by adamwathan** [comment] 2020-03-18 15:29
Closing as not a bug but happy to answer any more questions.

**Closed by adamwathan** 2020-03-18 15:29 UTC
Labels: bug

**Comment by mikemartin** [comment] 2020-03-18 22:13
@adamwathan I have a related question. I've been working on these form screen and needed to replace the default `outline-blue` shadow focus state to a simple green border on focus.
http://gethelp.surge.sh/report-issue.html

Looks like I need to override each field type. Would it be possible to control this with a default setting for all fields?

```
customForms: theme => ({
      default: {
        input: {
          '&:focus': {
            boxShadow: 'none',
            borderColor: theme('colors.green.200')
          },
          '&:hover': {
            borderColor: theme('colors.green.200')
          }
        },
        textarea: {
          '&:focus': {
            boxShadow: 'none',
            borderColor: theme('colors.green.200')
          },
          '&:hover': {
            borderColor: theme('colors.green.200')
          }
        },
        multiselect: {
          '&:focus': {
            boxShadow: 'none',
            borderColor: theme('colors.green.200')
          },
          '&:hover': {
            borderColor: theme('colors.green.200')
          }
        },
        select: {
          '&:focus': {
            boxShadow: 'none',
            borderColor: theme('colors.green.200')
          },
          '&:hover': {
            borderColor: theme('colors.green.200')
          }
        },
        checkbox: {
          '&:focus': {
            boxShadow: 'none',
            borderColor: theme('colors.green.200')
          },
          '&:hover': {
            borderColor: theme('colors.green.200')
          }
        },
        radio: {
          '&:focus': {
            boxShadow: 'none',
            borderColor: theme('colors.green.200')
          },
          '&:hover': {
            borderColor: theme('colors.green.200')
          }
        },
      },
    })
```

**Comment by Mvsvh** [comment] 2020-04-04 13:27
@adamwathan 
Would be nice to include cool-gray in the defaults since it's part of the tailwind color palette.
