### ISSUE TITLE
Problem with modal dialog when height of content is larger than browser height

### ISSUE THREAD

**Issue by pakali** [tailwindui/issues#131] opened 2020-04-02 09:33 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: Modals

**Describe the bug**
When the content of modal dialog is larger than height of browser user can not scroll content. 

**To Reproduce**
1. Select dialog modal component
2. Fill content with some large text
3. Try to scroll content

**Expected behavior**
User should be able to scroll content

**Screenshots**
...

**Browser/Device (if applicable)**
 - OS: Any
 - Browser: Safari and Chrome, probably Firefox too.
 - Version: Any

**Additional context**
...

**Comment by keithbrink** [comment] 2020-04-07 12:44
I had this issue as well; just FYI, you can add `overflow-auto max-h-96` to this tag: https://a.cl.ly/lluyPPNq

**Comment by jasonlbeggs** [comment] 2020-06-22 20:03
I'm going to close this for now as it's a duplicate of [this issue](https://github.com/tailwindui/issues/issues/42) and we're working on a fix. Thanks!

**Closed by jasonlbeggs** 2020-06-22 20:03 UTC
Labels: bug
