### ISSUE TITLE
Form-selects not the same height as inputs

### ISSUE THREAD

**Issue by tanthammar** [tailwindui/issues#210] opened 2020-05-29 10:17 UTC
I noticed that my `form-selects` does not look the same as on the demo site. 

In Chrome dev-tools I can see that there are `@media`  statements which alters the `font-size`. 
They are not included when I install Tailwind ui locally.  Which means that **form-selects are taller than the inputs whereas online they have the same height**.

Online I can see the @media statements exists in `iframe.css`.

- Why are they not included in tailwindui npm package?
- How do I get them to make form elements get the correct styling?

**Comment by tanthammar** [comment] 2020-05-29 10:25
This is in my package.json
```
"tailwindcss": "^1.4.6",
"@tailwindcss/ui": "^0.3.0",
"laravel-mix-tailwind": "^0.1.0",
```

This is my config:
``` js
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  purge: {
    content: [
      './app/**/*.php',
      './packages/**/*.php',
      './resources/**/*.html',
      './resources/**/*.js',
      './resources/**/*.jsx',
      './resources/**/*.ts',
      './resources/**/*.tsx',
      './resources/**/*.php',
      './resources/**/*.vue',
      './resources/**/*.twig',
    ],
    options: {
      defaultExtractor: (content) => content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || [],
      whitelistPatterns: [/-active$/, /-enter$/, /-leave-to$/, /show$/, /^sm:col-span-/],
    },
  },
  theme: {
    screens: {
      'sm': '640px',
      // => @media (min-width: 640px) { ... }

      'tablet': { 'max': '767px' },
      // => @media (max-width: 767px) { ... }

      'md': '768px',
      // => @media (min-width: 768px) { ... }

      'lg': '1024px',
      // => @media (min-width: 1024px) { ... }

      'xl': '1280px',
      // => @media (min-width: 1280px) { ... }
    },
    extend: {
      fontFamily: {
        sans: ['Nunito', ...defaultTheme.fontFamily.sans],
      },
      colors: {
        night: {
          darkest: '#2E3440',
          dark: '#3B4252',
          light: '#434C5E',
          lighter: '#4C566A',
        },
        snow: {
          dark: '#D8DEE9',
          medium: '#E5E9F0',
          light: '#ECEFF4',
        },
        frost: {
          green: '#8FBCBB',
          mint: '#88C0D0',
          dimmed: '#81A1C1',
          blue: '#5E81AC',
        },
        aurora: {
          red: '#BF616A',
          orange: '#D08770',
          yellow: '#EBCB8B',
          green: '#A3BE8C',
          pink: '#B48EAD',
        }
      }
    }
  },
  variants: {
    padding: ['responsive', 'first', 'last', 'hover'],
  },
  plugins: [
    require('@tailwindcss/ui')({
      layout: 'sidebar',
    })
  ],
}
```

**Comment by jasonlbeggs** [comment] 2020-06-04 20:08
Hey @tanthammar! I'm not able to reproduce the issue with your Tailwind config. Can you maybe post a HTML snippet that shows the issue on your machine so I can make sure it's not an issue with the HTML/classes in the HTML?

Thanks!

**Comment by jasonlbeggs** [comment] 2020-06-12 18:12
I'm going to close this for now. If you can provide an example that reproduces the issue, feel free to reopen it! Thanks!

**Closed by jasonlbeggs** 2020-06-12 18:12 UTC
Labels: bug
