### ISSUE TITLE
Content of Modals is not scrollable.

### ISSUE THREAD

**Issue by iyashpal** [tailwindui/issues#230] opened 2020-06-21 08:29 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: All Components.

**Describe the bug**
In my project, I want to list the user profile items in a modal. When I listed all profile items in the modal I am unable to access everything within the viewport. I can't scroll to content.

**To Reproduce**

**Expected behavior**
The content should be scrollable except modal header and footer.

**Screenshots**
![image](https://user-images.githubusercontent.com/19922707/85220046-402fea80-b3c6-11ea-8eb0-4c5c383d831d.png)

**Additional context**
For reference, please refer to the bootstrap modals. Bootstrap modals can handle content in all ways. We don't need to worry about content length.

**Comment by jasonlbeggs** [comment] 2020-06-22 20:03
I'm going to close this for now as it's a duplicate of [this issue](https://github.com/tailwindui/issues/issues/42) and we're working on a fix. Thanks!

**Closed by jasonlbeggs** 2020-06-22 20:03 UTC
Labels: bug
