### ISSUE TITLE
Comments for transitions after removing Alpine are incomplete

### ISSUE THREAD

**Issue by garth** [tailwindui/issues#194] opened 2020-05-07 10:05 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: All that I checked

**Describe the bug**

After removing Alpine and adding comments, the comments document transitions, but don't show which elements need to be toggled with show/hide.

**Expected behavior**

A comment that says someing along the lines of: Add class `hidden` to hide, remove the class `hidden` to show. before each element that has to be toggled.

**Comment by sevenseacat** [comment] 2020-05-08 14:49
Yep, just came across this as well. Some comments on the elements that should be used to toggle the show/hide would be great too.

**Comment by IMPMAC** [comment] 2020-05-14 15:40
I couldn't get the sidebar transitions to work in vue to match what the examples shows. The sidebar has an opacity transition when open opening and closing along with the slide transition

**Comment by adamwathan** [comment] 2020-06-04 17:07
Hey folks! The transitions always apply to the element directly under the comment 👍  We'll be adding working examples in Vue/React/Alpine in the coming months that should help out a lot here. Sorry for the confusion!

**Closed by adamwathan** 2020-06-04 17:07 UTC
Labels: bug

**Comment by garth** [comment] 2020-06-04 19:06
Hi @adamwathan,

Sorry if I wasn't quite clear enough in the bug description. The transition comment is correct and clear. But the problem is that the show/hide toggle comment is missing.

in the Alpine version you have `x-show="sidebarOpen", but there is no comment that describes this.

**Comment by alexvanzyl** [comment] 2020-09-09 18:29
Hi @adamwathan,

I am having the same issue here using Vue.js.

As per the snippet below, I added the transitions per the comments, the problem is when the `v-show` directive is triggered on the parent element the transitions are ignored. If I add the `v-show` directives within the first child elements for each transition and remove it from the parent, the transitions will work but once you close the sidebar you still have the canvas overlapping the dashboard, so you can't use the menu button. Trying to see if I can find a workaround. 


```
  <div class="h-screen flex overflow-hidden bg-gray-100">
    <!-- Off-canvas menu for mobile -->
    <div class="md:hidden" v-show="isOpen">
      <div class="fixed inset-0 flex z-40">
        <!--
        Off-canvas menu overlay, show/hide based on off-canvas menu state.

        Entering: "transition-opacity ease-linear duration-300"
          From: "opacity-0"
          To: "opacity-100"
        Leaving: "transition-opacity ease-linear duration-300"
          From: "opacity-100"
          To: "opacity-0"
        -->
        <transition
          enter-active-class="transition-opacity ease-linear duration-300"
          enter-class="opacity-0"
          enter-to-class="opacity-100"
          leave-active-class="transition-opacity ease-linear duration-300"
          leave-class="opacity-100"
          leave-to-class="opacity-0">
        >
          <div class="fixed inset-0">
            <div class="absolute inset-0 bg-gray-600 opacity-75"></div>
          </div>
        </transition>
        ...
```

**Comment by adamwathan** [comment] 2020-09-11 12:07
Hey @alexvanzyl! The trick with Vue is to use an extra transition around the parent and give it a duration matching the children:

```html
  <div class="h-screen flex overflow-hidden bg-gray-100">
    <!-- Off-canvas menu for mobile -->
    <transition :duration="300">
      <div class="md:hidden" v-show="isOpen">
        <div class="fixed inset-0 flex z-40">
          <!--
          Off-canvas menu overlay, show/hide based on off-canvas menu state.

          Entering: "transition-opacity ease-linear duration-300"
            From: "opacity-0"
            To: "opacity-100"
          Leaving: "transition-opacity ease-linear duration-300"
            From: "opacity-100"
            To: "opacity-0"
          -->
          <transition
            enter-active-class="transition-opacity ease-linear duration-300"
            enter-class="opacity-0"
            enter-to-class="opacity-100"
            leave-active-class="transition-opacity ease-linear duration-300"
            leave-class="opacity-100"
            leave-to-class="opacity-0">
          >
            <div class="fixed inset-0">
              <div class="absolute inset-0 bg-gray-600 opacity-75"></div>
            </div>
          </transition>
          ...
```

**Comment by alexvanzyl** [comment] 2020-10-11 10:35
Hey @adamwathan that did the the trick :) Thanks a lot!
