### ISSUE TITLE
Wide Lists: With right-justified second column

### ISSUE THREAD

**Issue by alihamed** [tailwindui/issues#168] opened 2020-04-22 06:20 UTC
<img width="1266" alt="Screen Shot 2020-04-21 at 11 19 19 PM" src="https://user-images.githubusercontent.com/5684742/79947284-8e585a00-8426-11ea-9c81-c136b4ee1b96.png">

the code for this wide list seems to not match the preview.

**Comment by alihamed** [comment] 2020-04-22 06:21
to replicate, copy the code and paste it in a new file...it has this weird dot in the upper left.

**Comment by jasonlbeggs** [comment] 2020-05-30 01:17
I'm not able to reproduce this issue. Can you confirm you have the Tailwind UI plugin installed in your project and that you're still seeing the bug? I'm going to close the issue for now, but if this is still a bug for you, feel free to reopen it. Thanks!

**Closed by jasonlbeggs** 2020-05-30 01:17 UTC
Labels: bug
